### PR TITLE
Update producer.lua

### PR DESCRIPTION
**Pull request by firefliesx**
Fix the bug of timestamp when sending msg to kafka.

### CODE REVIEW

**Comment by DG-Wangtao** [comment]
@firefliesx @doujiang24  Hi, I meet the same error on Kafka 3.3.1, will you finish this? Thanks.

**Comment by doujiang24** [comment]
Oh, sorry for the long delay.
@DG-Wangtao Could you help to confirm this PR fixed the error on your side?
@firefliesx The CI failed, could you help to take a look? Thanks.
Otherwise, it looks good to me.

**Comment by DG-Wangtao** [comment]
I test this change and get an error 
`[error] 1111#0: *1338 [lua] producer.lua:268: buffered messages send to kafka err: closed, retryable: true, topic: audit-log, partition_id: 0, length: 1, context: ngx.timer`
So I think there are some works need to be done.

**Comment by DG-Wangtao** [comment]
I test this change and get an error 
`[error] 1111#0: *1338 [lua] producer.lua:268: buffered messages send to kafka err: closed, retryable: true, topic: audit-log, partition_id: 0, length: 1, context: ngx.timer`
So I think there are some works need to be done.

**Comment by DG-Wangtao** [comment]
I test this change and get an error 
`[error] 1111#0: *1338 [lua] producer.lua:268: buffered messages send to kafka err: closed, retryable: true, topic: audit-log, partition_id: 0, length: 1, context: ngx.timer`
So I think there are some works need to be done.

**Comment by doujiang24** [comment]
Thanks @DG-Wangtao 
Are you interested to continue this PR? I'm happy to review it.

**Comment by DG-Wangtao** [comment]
Thanks, @doujiang24 
I will try to, but maybe not quickly.

**Comment by DG-Wangtao** [comment]
@doujiang24 @firefliesx  Hi, recently my friend @jasine  find out this PR works well if set `api_version = 2` explicitly, like this 
```lua

  local producer_config = {
    -- settings affecting all Kafka APIs (including Metadata API, Produce API, etc)
    socket_timeout = conf.timeout,
    keepalive_timeout = conf.keepalive,
    -- other settings ... ....
    api_version = 2,
  }
  return kafka_producer:new(broker_list, producer_config, cluster_name)
```

So please merge this pr safely, thanks.

**Comment by doujiang24** [comment]
@DG-Wangtao Thanks for your confirmation. But the CI is failed, and still needs to address, would you please take a look?

**Comment by DG-Wangtao** [comment]
I create another pr #149, a maintainer approval is needed there to run the CI workflow.

**Comment by doujiang24** [comment]
@firefliesx @DG-Wangtao Thanks! #149 is merged, so, closing this.

**Comment by DG-Wangtao** [comment]
Hi @doujiang24 , would you please update this package in LuaRocks ?

**Comment by doujiang24** [comment]
@DG-Wangtao sorry for the late, just updated. Please ping me if you have any more questions.

**Pull request closed without merging**
